spring:
  profiles:
    active: uat # dev, prod
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
app:
  name: blog
  authentication:
    jwtSecret: JWTSuperSecretKey
    jwtExpirationInMs: 1800000

logging:
  level:
    liquibase: INFO